### ISSUE TITLE
Use for BP3D

### ISSUE THREAD

**Issue by Yuri6037** [dimforge/nalgebra#1005]
Hello,

I've just found your crate while searching for some base math library that I could use in BP3D. I found your crate interesting however I've found a lot of convenience issues:

- Impossible to multiply 2 Vector2 (v * v1 -> compile error)
- Impossible to multiply 2 Vector3 (v * v1 -> compile error)
- Impossible to multiply 2 Vector4 (v * v1 -> compile error)
- Impossible to add 2 points (compile error again)
- Impossible to multiply 2 points (compile error again)
- Impossible to subtract 2 points (compile error again)

Can these convenience issues be fixed?

**Comment by sebcrozet** [comment]
Regarding the semantics of points, I would suggest reading [that stackoverflow answer](https://math.stackexchange.com/a/645827) which does a great analogy with time. In particular, the example you provided is using a point when it should actually use a vector for the `offset` (because the name "offset" suggests that you are talking about a displacement instead of a position in space):

```rust
let offset = Vector2::new(ScrW / 2.0, ScrH / 2.0);
let pos = Point2::new(1.0, 1.0) + offset;
```

> Maybe you should consider handling vectors differently as multiplying vectors is a common operation in 3D games.

Unless Rust gets support for specialization, that’s not possible.
Regarding `.component_mul` being too complicated, I guess we could come up with a shorter name that still make sense.

> EDIT3: Well considering these limitations/simplicity issues I'll probably have to make my own math lib.

You may want to take a look at other math libs in Rust (`cgmath`, `glam`, etc.), which may have the level of simplicity you seek.

**Comment by Yuri6037** [comment]
> Regarding the semantics of points, I would suggest reading [that stackoverflow answer](https://math.stackexchange.com/a/645827) which does a great analogy with time. In particular, the example you provided is using a point when it should actually use a vector for the `offset` (because the name "offset" suggests that you are talking about a displacement instead of a position in space):
> 
> ```rust
> let offset = Vector2::new(ScrW / 2.0, ScrH / 2.0);
> let pos = Point2::new(1.0, 1.0) + offset;
> ```
> 
> > Maybe you should consider handling vectors differently as multiplying vectors is a common operation in 3D games.
> 
> Unless Rust gets support for specialization, that’s not technically possible. Regarding `.component_mul` being too complicated, I guess we could come up with a shorter name that still make sense.
> 
> > EDIT3: Well considering these limitations/simplicity issues I'll probably have to make my own math lib.
> 
> You may want to take a look at other math libs in Rust (`cgmath`, `glam`, etc.), which may have the level of simplicity you seek.

I see what you mean about points. I'm not sure if I'd call this a point though. At least you can add a point with a vector but you can't multiply a point by a vector which in this case is weird.

The issue with component_mul is not how long is the name but instead the fact that because this is a function you have to call `v.component_mul(v1.component_mul(v2))` which already starts to be messy.
Couldn't you implement this operator * for only single column matrices?
Couldn't you consider implementing a different operator exclusively for component wise multiplication? Numpy does this already with @ for matrix multiplication and * for element wise multiplication. Maybe you could use '^' or '%' as I don't think there's any '@' operator in Rust.

**Comment by Yuri6037** [comment]
> > I know this is usually considered bad practice in Rust, but this could be set behind a crate feature disabled by default.
> 
> Even if it’s behind a feature and disabled by default, it’s still bad practice, so we should probably not promote this kind of usage of operator overloading.

This operator issue is really a blocker for me. It's too inconvenient to use the .component_mul it would be very hard to get the operation order right with .component_mul. This is why I really need a way to do this from an operator. Maybe you could instead consider inverting: * becomes component mul and .mul becomes matrix mul? I know that would be a breaking change but at least that would make vector math MUCH better. In computer graphics chained matrix multiplication is less used than vector math

> 
> > I should have asked more specific questions:
> > 
> > * Is your Perspective class creating right-handed or left handed projection matrices?
> > * Is your Perspective class mapping depth to [-1; 1] or [0; 1]?
> 
> The `Perspective` class is left-handed and maps depth to `[-1; 1]` follows OpenGL conventions. The `nalgebra-glm` crate gives other perspective matrix conventions (but they are not encapsulated by a dedicated type).

Thanks for this info.

**Comment by sebcrozet** [comment]
> Maybe you could instead consider inverting: * becomes component mul and .mul becomes matrix mul? I know that would be a breaking change but at least that would make vector math MUCH better. In computer graphics chained matrix multiplication is less used than vector math. This inversion could also be behind a feature flag.

That’s not an option.
Most of what I do is related to computer graphics, and I use very rarely componentwise multiplication. And it is even more unlikely to have to chain multiple componentwise multiplications in a single line/expression. But of course, different people have different needs, so I would be very interested (out of curiosity) to see an actual meaningful piece of code that relies so extensively on componentwise multiplications in order to undesrtand the issue better.

The proposal about `comp` is interesting, but it can’t be added to `nalgebra` itself as would introduce even more complexity to `nalgebra` type system (though that’s a good way to deal with that using an extension trait on your end). Also I am not sure how this is any less verbose than introducing a shorter name for componentwise multiplication:

```rust
let v1 = v.cmul(&Vec3f::new(2.0, 0.0, 0.0)).cdiv(&Vec3f::new(0.5, 1.0, 1.0));
```

The order of operations is as clear is with an operator here because in both case the "operator" (`*` or `.cmul(`) are in the exact same places.

**Comment by Yuri6037** [comment]
> > Maybe you could instead consider inverting: * becomes component mul and .mul becomes matrix mul? I know that would be a breaking change but at least that would make vector math MUCH better. In computer graphics chained matrix multiplication is less used than vector math. This inversion could also be behind a feature flag.
> 
> That’s not an option.
> 
> Most of what I do is related to computer graphics, and I use very rarely componentwise multiplication. And I am even more unlikely to have to chain multiple componentwise multiplications in a single line/expression. But of course, different people have different needs, so I would be very interested (out of curiosity) to see an actual meaningful piece of code that relies so extensively on componentwise multiplications in order to undesrtand the issue better.
> 
> The proposal about `comp` is interesting, but it can’t be added to `nalgebra` itself as would introduce even more complexity to `nalgebra`’s type system (though that’s a good way to deal with that using an extension trait on your end). Also I am not sure how having to call `.comp()` is any less verbose than introducing a shorter name for componentwise multiplication:
> 
> ```rust
> let v1 = v.cmul(&Vec3f::new(2.0, 0.0, 0.0)).cdiv(&Vec3f::new(0.5, 1.0, 1.0));
> ```
> 
> The order of operations is as clear is with an operator here because in both case the "operator" (`*` or `.cmul(`) are in the exact same places.

I understand better `let v1 = (v.comp() * Vec3f::new(2.0, 0.0, 0.0)).comp() / Vec3f::new(0.5, 1.0, 1.0);` rather than `let v1 = v.cmul(&Vec3f::new(2.0, 0.0, 0.0)).cdiv(&Vec3f::new(0.5, 1.0, 1.0));`
I can't tell you why exactly but I have an easier time reading with operators rather than with functions. In addition using my system is simpler as you don't have to explicitly '&'.

**Comment by Yuri6037** [comment]
> I think introducing `cmul` and `cdiv` is a good idea, as `component_mul` is indeed rather verbose.
> 
> `nalgebra` already does the right thing in rejecting Vector * Vector. In Rust, the meaning of operators is quite clear: `*` is multiplication, `+` is addition, `%` is remainder, `^` is bitwise exclusive or, and so on. So the only potentially applicable operator is `*`. Semantically speaking, `nalgebra` provides matrices and vectors, for which multiplication **must** correspond to matrix multiplication. Certainly otherwise the meaning of multiplying a matrix with a vector would not even be well-defined or obvious. Practically speaking it's also by far the most useful. Compare this with, say, `ndarray` which provides **arrays** and uses element-wise operations for all unary/binary operators. For arrays, a consistent element-wise interpretation of binary operations seems reasonable.
> 
> Changing the semantic meaning of multiplication from matrix multiplication to component-wise multiplication depending on the dimensions of the operands seems ill-advised. When reading the code, you'd have to carry more mental context in order to determine which operation is applied. And moreover, if `a * b` were valid for two vectors, why should it denote the component-wise product? Might as well be the dot product in that case, which suggests an unfortunate ambiguity. As @sebcrozet suggested, the Hadamard / component-wise product comes up every now and then in computer graphics and science, but my experience suggests that matrix multiplication is by **far** the more common operation between the two.

That's your opinion. It turns in my case I can have quite a few of pos * scale and scale * pos kind of situations so in my case the Hadamard product is also common.
I understand that it is usefull to multiply vectors by matrices especially in computer graphics but component wise vector by vector multiplication is also common (at least in my cases).
Ideally we would like multiply operator for both depending on context (that's what most math APIs for CG do).
Either way I understand that you do not want to apply these convenience functions, this is why I've searched for a trait hack which I could use to brink the missing functionality which is btw available on ALL math APIs used in most engines (Unreal, Unity, etc...)
It's a shame this lib advertises as being made for computer graphics but lacks such a common feature.

**Comment by Yuri6037** [comment]
> `Similarity`

As you've said it Similarity does not support vector based scaling which is a requirement for my engine.

You'd accept the trait hack as a PR? Really? If you're sure no problem I can do it.
