### ISSUE TITLE
Rendering APIs

### ISSUE THREAD

**Issue by Yuri6037** [dimforge/nalgebra#1006]
In order to use nalgebra with low-level rendering APIs I need access to raw contiguous arrays of floats for matrices, vectors and quaternions.

I've read doc for .as_ptr; however a few points seam unclear:

I have some questions related to your data structure. 
- Is .as_ptr returning a pointer to the first element of a raw contiguous array of floats for f32 types of matrices?
- Are you using column major or row major for the data returned by .as_ptr?

`If the matrix is not empty, this pointer is guaranteed to be aligned and non-null.`
- What do you mean by 'empty' matrix? Zero matrix? Identity matrix?
- Does this mean that this function achieves UB if the matrix is empty?
- What exactly does this function return if the matrix is empty?
- Is there any way to detect if the matrix is empty?

**Comment by Andlon** [comment]
> > To add to that: as a consequence, if a matrix empty, it has zero elements so it would not be sound to read or write from/to any such pointer, since this is just an out of bounds read/write.
> 
> Yeah I understood from your first post. I never expected empty to mean 'zero sized'. Of course I don't need any 'zero sized' matrix it's useless for a 3D rendering engine.

Well, it just means the same as "empty" does for any other collection in Rust. I can't think of a better name for it at least... That's fair - it comes up a lot in other applications though.

**Comment by Yuri6037** [comment]
That's a good idea maybe you could add to the doc some documentation about the internal data structure this way future people won't need to ask what I've just asked. In addition also mention that empty means 'zero sized'.
