### ISSUE TITLE
Bug (?): MatrixSlice with fixed length can no longer be converted into an primitive array via From/Into

### ISSUE THREAD

**Issue by AlterionX** [dimforge/nalgebra#1010]
Title.

Upon migrating from 0.18, this code no longer seems to work. I've been digging around and trying to find an equivalent without much luck. I could manually create the array, but if there's a better way...

```rs
fn stuff() -> [f32; 3] {
    let m: Matrix3<f32> = blah;
    return m.column(n).into();
}
```

**Comment by sebcrozet** [comment]
Hi! Thank you for pointing this out. A workaround could be `m.column(n).into_owned().into()`.

**Comment by Andlon** [comment]
@sebcrozet: it would probably be a good idea to include a simple test to
prevent similar regressions in the future, perhaps?

**Comment by AlterionX** [comment]
Thanks!
