### ISSUE TITLE
UnitDualQuaternion::sclerp() fails to interpolate equal rotations

### ISSUE THREAD

**Issue by Andlon** [dimforge/nalgebra#1013]
Example:

```rust
let q1 = UnitDualQuaternion::from_rotation(UnitQuaternion::identity());
let q2 = UnitDualQuaternion::from_rotation(UnitQuaternion::identity());
q1.sclerp(&q2, 0.5);
```
panics with message:
```
DualQuaternion sclerp: ambiguous configuration.
```

Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2d0788827c911f814132f41ce3e247d4

I realize that 180 degree rotation is ambiguous for interpolation, but 0 degrees ought to be unambiguous. I'd fix this myself but I'm not deep enough into the math to be confident about the fix (and I'm too involved with other things to get into it right now).

Maybe @tpdickso, @chinedufn or @ChristopherRabotin from #487 are able to chime in here.

**Comment by sebcrozet** [comment]
Closing this as the PR fixing it is merged.
