### ISSUE TITLE
The pow/pow_mut methods are not correct

### ISSUE THREAD

**Issue by wjyoumans** [dimforge/nalgebra#1021]
The `pow` and `pow_mut` methods are incorrect. Looking at the source it seems the logic in the exponentiation-by-squares loop is wrong, so with input exponent `e` it will return M to the power `e+1`. Unrelated, it also looks like there is an extra unused multiplication and copy before exiting the loop: the steps `multiplier.mul_to(&multiplier, &mut buf)` and the copy after that go unused once we hit the return statement.

Example: 
```
let mut m = Matrix2::new(0.0,1.0,1.0,0.0);
m.pow_mut(1);
```

The matrix should be unchanged here but instead we get `m^2` which is the identity.

**Comment by Andlon** [comment]
Ouch. This really ought to have been caught by some very basic tests!

@sebcrozet: perhaps we could try to be a little bit more strict about adequate testing in new PRs? Unfortunately broken functionality like this may do more harm than good...

**Comment by sebcrozet** [comment]
> @sebcrozet: perhaps we could try to be a little bit more strict about adequate testing in new PRs? Unfortunately broken functionality like this may do more harm than good...

Sounds good, we should require some proptest tests to be added alongside the feature.

**Comment by Ten0** [comment]
I was about to open this.
Here's another example:
```rust
fn main() {
    let m = nalgebra::DMatrix::from_diagonal_element(3, 3, 2f64);
    println!("{}", m.pow(1).unwrap());
}
```

Is this library unmaintained or something for something as basic to take as long to get fixed?

@vihdzp
