### ISSUE TITLE
Matrix slicing without specifying the last element

### ISSUE THREAD

**Issue by szobov** [dimforge/nalgebra#1030]
Hi there,
Thanks for the amazing project.
I have a question regarding matrix/vector slicing.
In `numpy` I can write such code-snippet:
```
In [1]: import numpy as np

In [2]: a = np.zeros((1, 10))

In [3]: a
Out[3]: array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]: a[0, 1:] = 42.0

In [5]: a
Out[5]: array([[ 0., 42., 42., 42., 42., 42., 42., 42., 42., 42.]])
```
But I didn't figure out a way of how I can do [0, **1:**] in nalgebra.
Thanks for any advice.
Cheers.

**Comment by Andlon** [comment]
If I understand correctly, I think the following should accomplish what you want:
```rust
a.index_mut((0, 1..)).fill(42.0);
```

**Comment by szobov** [comment]
yes, that's what I was looking for.
thanks!
