### ISSUE TITLE
Can't transpose matrix: expected struct `Dynamic`, found struct `Const`

### ISSUE THREAD

**Issue by szobov** [dimforge/nalgebra#1033]
Hi there,

Could you please point me out in the documentation, where I can find the solution to such an issue?
I have a function, that receives a dynamic vector and transposes it in case of an unexpected shape.
```
fn calculate(&self, x_mean_input: &DVectorF, P_covarience: &DMatrixF) -> DMatrixF {
        let (x_row, _) = x_mean_input.shape();
        let x_mean = x_mean_input.clone_owned();
        if x_row != 1 {
            x_mean = x_mean.transpose();
        }
```
but a compilation fails with the message:
```
61 |             x_mean = x_mean.transpose();
   |                      ^^^^^^^^^^^^^^^^^^ expected struct `Dynamic`, found struct `Const`
   |
   = note: expected struct `na::Matrix<_, Dynamic, Const<1_usize>, VecStorage<_, Dynamic, Const<1_usize>>>`
              found struct `na::Matrix<_, Const<1_usize>, Dynamic, VecStorage<_, Const<1_usize>, Dynamic>>`
```
I also tried:
```
        let x_mean =  match x_row {
            1 => x_mean_input.clone_owned(),
            _ => x_mean_input.transpose()
        };
```
and this:
```
        if x_row != 1 {
            x_mean.transpose_mut();
        }
```
but nothing compiles.

Even if I move this logic out of the function, to make a user transpose the vector first, it fails with another error:
```
        let x = na::DVector::from_vec(vec![1., 2.]).transpose();
        let res = sigmas.calculate(&x, &P);
```
```
error[E0308]: mismatched types
   --> src/lib.rs:116:36
    |
116 |         let res = sigmas.calculate(&x, &P);
    |                                    ^^ expected struct `Dynamic`, found struct `Const`
    |
    = note: expected reference `&na::Matrix<f64, Dynamic, Const<1_usize>, VecStorage<f64, Dynamic, Const<1_usize>>>`
               found reference `&na::Matrix<{float}, Const<1_usize>, Dynamic, VecStorage<{float}, Const<1_usize>, Dynamic>>`
```
I would appreciate it if you point me to where I can read about solving these problems in general.
Thanks a lot!

**Comment by metric-space** [comment]
For the flexibility you seem to want, I think it's best to switch from DVector to DMatrix.
The root problem is the row and column dimension type  pre and post transpose are not lining up

**Comment by Andlon** [comment]
I don't see why you want to "transpose in case of an unexpected shape". I would first revisit this assumption: I can't imagine ever wanting to do this in Rust - though there might be a valid case for it nonetheless, of course. This sounds like something you might want to do in Python, but in Rust you usually model your problems in a less ambiguous way.

If you *really* want to be able to work with a vector that is represented as either `Nx1` **or** `1xN`, then you probably have to work with `DMatrix` as @metric-space  suggests.

**Comment by szobov** [comment]
Hey @Andlon @metric-space 
Thank you both for the help, I moved from DVector to DMatrix and it works smoothly.

It's a bit counter-intuitive for me, why when I transposed and vector it becomes differently typed from the original one, but anyway, I will use DMatrix instead.

Cheers

**Comment by sebcrozet** [comment]
@szobov 
> It's a bit counter-intuitive for me, why when I transposed and vector it becomes differently typed from the original one, but anyway, I will use DMatrix instead.

In `nalgebra`, the dimensions of matrices are part of the matrix’s type. There are two "kinds" of dimension types:
- `Const<INTEGER>` (for example `Const<1>`, `Const<4>`, etc.) which are used when the dimensions are known/fixed at compile-time.
- `Dynamic` which is for dimensions known at runtime.

If you take the case of the `DVector` that you used, it is an alias for a matrix type with dimensions `Dynamic x Const<1>`, which means that this type can hold any number of rows, but must have exactly one column at all time. Therefore, your `x_mean` variable can only contain matrices which are known to have exactly 1 column.

When you do `x_mean.transpose()`, you are creating a new matrix which is known, at compile-time, to have the dimensions `Const<1> x Dynamic`: it is known to have 1 row, and any number of columns. This doesn’t match the original type of `x_mean`, so you can’t do `x_mean = x_mean.transpose()`.

By using a `DMatrix`, you have a matrix with dimensions `Dynamic x Dynamic`. This means that none of the matrix dimensions have to be known at compile time. Therefore, doing `x_mean.transpose()` where `x_mean` is a `DMatrix` returns another matrix with dimensions `Dynamic x Dynamic`, which does match the initial type of `x_mean`.

I hope this helps clarifying things a bit.

**Comment by szobov** [comment]
wow, thanks a ton @sebcrozet 
It makes much more sense for me now, and I see this is the way of verifying the correct shapes in compile time.
I started to play with algebra after NumPy, so did some assumptions that work in a similar way.
Again, thanks a lot for a very good explanation!
