### ISSUE TITLE
Matrix::select_rows and Matrix::select_columns requires T: Zero

### ISSUE THREAD

**Issue by haibane-tenshi** [dimforge/nalgebra#1046]
The fact is somewhat surprising when trying to use matrix types with non-numerical data.
Internal implementation doesn't seem to rely on the trait, can the restriction be lifted?

**Comment by CattleProdigy** [comment]
@haibane-tenshi Looks like `select_rows()` and `select_columns()` got grouped (not unreasonably) with `lower_triangular()` and `upper_triangular()` into one `impl` block with `T:Zero`. The triangular methods use `T::zero()` to fill out the rest of extracted matrix. You should be able to move the select methods into their own block without  `T:Zero` in `src/base/edition.rs` and submit a PR.

**Comment by haibane-tenshi** [comment]
Sure, I'll make a PR when I get my hands on it. The question mostly was if it is ok to lift it or not :)

**Comment by haibane-tenshi** [comment]
PR got merged, closing issue.
