### ISSUE TITLE
Feature request: generalized eigenvalues / QZ decomposition

### ISSUE THREAD

**Issue by mkeeter** [dimforge/nalgebra#1056]
I'm looking into implementing a particular numerical algorithm using `nalgebra`, and it requires solving for the [generalized eigenvalues](https://en.wikipedia.org/wiki/Eigendecomposition_of_a_matrix#Generalized_eigenvalue_problem) of a pair of matrices.

This is related to [QZ decomposition](https://en.wikipedia.org/wiki/Schur_decomposition#Generalized_Schur_decomposition), which SciPy [implements using `gges`](https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/linalg/_decomp_qz.py#L144) from LAPACK.

It would be great if `nalgebra` exposed a similar function (or if there's a way to do it already and I haven't found it)!

**Comment by metric-space** [comment]
@mkeeter  Haven't worked with the LAPACK part of `nalgebra`, so am interested in making a PR exposing said function and willing to do the work (assuming you aren't in the process of doing so). If you can wait for 2 weeks from now, can have the PR up (again if you haven't already)

On a side note: big fan of your work

**Comment by mkeeter** [comment]
Awesome – I'm *not* in the process of writing my own PR, so I'd say to go for it!
