### ISSUE TITLE
Component wise raising to a power

### ISSUE THREAD

**Issue by ryanswilson59** [dimforge/nalgebra#1061]
I can see that there is a component wise power operation in nalgebra-glm, is there something like this without pulling another dependency. Specifically I am trying to take the component wise (inverse)square root of a vector.

**Comment by metric-space** [comment]
from https://github.com/dimforge/nalgebra/blob/dev/src/base/matrix.rs#L762

since `vector` is a `matrix` in disguise (see https://github.com/dimforge/nalgebra/blob/dev/src/base/matrix.rs#L42)

you should be able to do something like `your_vector.map(|x| x.powf(0.5))`
