### ISSUE TITLE
Is there no way to assign into a mutable slice?

### ISSUE THREAD

**Issue by IndianBoy42** [dimforge/nalgebra#1063]
For some specific cases we have `set_row, set_col` etc. But there are a lot more ways to slice. I expected there to be a method `.assign()` or `.set()` on slices that would copy all the elements from the rhs

**Comment by sebcrozet** [comment]
You can use `.copy_from(&rhs)`.

**Comment by IndianBoy42** [comment]
Ah, there it is. sorry I was looking for set or assign.
