### ISSUE TITLE
`macro` feature is actually called `macros`

### ISSUE THREAD

**Issue by wucke13** [dimforge/nalgebra#1073]
https://github.com/dimforge/nalgebra/blob/dev/nalgebra-macros/src/lib.rs#L114
vs
https://github.com/dimforge/nalgebra/blob/dev/Cargo.toml#L25

**Comment by Andlon** [comment]
Well spotted. Do you feel up to making a PR with a fix, @wucke13? Would be very much appreciated! :)

**Comment by wucke13** [comment]
Yes sure, I can do it. However, first we need to decide which one is the
correct spelling :)

In in favor of macro, so singular.

**Comment by Andlon** [comment]
@wucke13: I think we should keep `macro` for two reasons:

- To avoid a breaking change.
- There are in fact several macros enabled by this feature (`vector`, `dvector`, `matrix`, `dmatrix`), with more to come in the future.

**Comment by Ralith** [comment]
@Andlon I think you meant to write `macros`?

**Comment by wucke13** [comment]
Hi, I opened the PR :) #1077
