### ISSUE TITLE
LU f32 f64

### ISSUE THREAD

**Issue by esoteloferry** [dimforge/nalgebra#1079]
Hi, 
I am using LU to solve linear system to get eigenvectors. Found that using f32 does not work but with f64 yes. 

I wrap up the error in a repo, it consists of 2 degrees of freedom problem and  it fails when calculating second eigenvector. 

To reproduce error: https://github.com/esoteloferry/error_f32_LU_nalgebra   , once installed run `cargo test -- --nocapture`

Related issues : https://github.com/dimforge/nalgebra/issues/348. (closed but not solved)

Following the comment on related issue. The decomposition LU that fails is done in a matrix like below, its determinant is zero. Therefore following documentation that says LU and QR are to be used on invertible matrices but why f64 runs ok and its result is correct?
1.366  -1
-0.5.  0.366

The solution provided by LU f64 is actually correct , I cross checked it with my book example. 

Extra: I also added Cholesky f32 & f64 just to test. But both of them fail, not so sure, maybe matrix does not comply with hermitian-positive-definite ( I still don't get what it means ).

**Comment by Andlon** [comment]
Hi @esoteloferry, could you please be more specific about the particular issue you're having?

From a brief look at your code and your description, it looks as if you are trying to use `LU` to solve a singular system of equations. This is not expected to work, as your system needs to be invertible/non-singular for this to be meaningful.

If you are trying to obtain eigenvectors, then you should rather use `SymmetricEigen` if your matrix is symmetric. If it is not, I'm not sure if `nalgebra` offers anything for complex eigenvectors at the moment...

**Comment by esoteloferry** [comment]
Hi @Andlon  , I made a mistake in my formulation to find eigenvectors , it is true that I was trying to solve a singular system of equations. Making the correct formulation and the matrix is not singular and LU f32 works just fine. Issue can be closed.
