### ISSUE TITLE
Using `Const<4>` instead of `Const<{ U4::USIZE }>` is better for rust-analyzer

### ISSUE THREAD

**Issue by digama0** [dimforge/nalgebra#1097]
From https://github.com/rust-analyzer/rust-analyzer/issues/11803#issuecomment-1076706851 :

> There is literaly no const eval in const generics yet, so `Const<{ four }>` is `Const<_>`. We can handle this special case easily, but the constants in nalgebra are very complex and evaluating them needs trait resolution (#4558) + lowering const generics to body (#7434) + evaluating assoc consts with generic parameters. Short term solution here IMO is replace `type u4 = Const<{ typenum::U4::USIZE }>` with `type U4 = Const<4>` in the nalgebra source code, which is an internal and invisible to user change.

Would this be a reasonable change to make? Rust analyzer has a lot of trouble with nalgebra's types, and this is a big impediment to using the crate in beginner settings. Arguably this is a problem that rust analyzer should solve, but if a simple fix like this helps it seems worthwhile.

**Comment by sebcrozet** [comment]
Hi! Yes, this can easily be done. I agree we should make the change if it makes it easier for rust-analyzer.
