### ISSUE TITLE
the trait `RelativeEq<_>` is not implemented for `OPoint<f32, Const<2_usize>>`

### ISSUE THREAD

**Issue by kgreenek** [dimforge/nalgebra#1102]
I have a point struct defined as a simple alias for the nalgebra point type with f32:

```rust
pub type Point<const D: usize> = na::Point<f32, D>;
pub type Point2 = Point<2>;
pub type Point3 = Point<3>;
```

However, whenever I try to use it with RelativeEq, I get the error in the title.

```rust
assert!(approx::relative_eq!(Point2::new(0.0f, 0.0f), Point2::new(0.0f, 0.0f)));
```

Do I need to bring something else into scope? It was working previously before I upgraded nalgebra from 0.22 to 0.31 and migrated to using the new const generics.

**Comment by sebcrozet** [comment]
Hi! Are you using the same version of `approx` as the one used by `nalgebra`?

**Comment by kgreenek** [comment]
Good catch! I had not updated my version of approx after updating nalgebra. Updating approx fixed the problem. Thank you!
