### ISSUE TITLE
nalgebra::Matrix is optimal only for column major order access

### ISSUE THREAD

**Issue by JohnScience** [dimforge/nalgebra#1118]
Hello!

I was very surprised to find out that nalgebra::Matrix imposes indexing order. By indexing order I mean the order on the set of pairs of indices `(i,j)`.

For example, for the following matrix

$$
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

its values in memory would be ordered like this for column-major order:

$$
\begin{bmatrix}
\text{0x0} & \text{0x1} & \text{0x2} & \text{0x3} \\
a & c & b & d \\
(0,0) & (1,0) & (0,1) & (1,1)
\end{bmatrix}
$$

and like this for row-major order:

$$
\begin{bmatrix}
\text{0x0} & \text{0x1} & \text{0x2} & \text{0x3} \\
a & b & c & d \\
(0,0) & (0,1) & (1,0) & (1,1)
\end{bmatrix}
$$

 Indexing order impacts performance because row-major order traversal on column-major matrix would cause absurd amount of cache misses unless matrices fit in the cache (=small).

Row-major order traversal is used in [Gaussian](https://en.wikipedia.org/wiki/Gaussian_elimination) and [Gauss-Jordan](https://online.stat.psu.edu/statprogram/reviews/matrix-algebra/gauss-jordan-elimination) elimination algorithms.

The problem can be solved by separating matrix indices (the binary indices) from in-storage indices (of type `usize`). This additional layer of abstraction must be easy for the compiler to optimize away.

**Comment by sebcrozet** [comment]
I agree that the benefit doesn’t sound worth the added complexity and maintenance burden.
If we do find a strong reason to support row-major in the future, this can’t be implemented (without major added complexity) before Rust fully supports specialization anyway.
