### ISSUE TITLE
Porting from Eigen to nalgebra

### ISSUE THREAD

**Issue by unconverged** [dimforge/nalgebra#1143]
Hi! I'm thinking of porting some of my codes to rust from C++ and I need linear algebra. nalgebra seems to be the proper choice here. In C++ I use [Eigen](https://eigen.tuxfamily.org/index.php?title=Main_Page) for linear algebra. However, with Eigen I make a heavy use of [Matrix Maps](https://eigen.tuxfamily.org/dox/classEigen_1_1Map.html) that let me wrap a plain array of numbers and treat these numbers as matrix elements. This approach lets me store the data as an array and use matrix-related operations when needed, without instantiating a full matrix object (i.e. no need to copy the data from an array to matrix-controlled memory).

Does nalgebra support something like this? To sum up, I need to be able to use matrix operations over an array of numbers without copying any data.

**Comment by Andlon** [comment]
Check out the [from_slice_generic](https://docs.rs/nalgebra/latest/nalgebra/base/type.MatrixSliceMutMN.html#method.from_slice_generic) method on the matrix slice types - can be used both for immutable and mutable matrix slices. Hope that helps!

**Comment by Ralith** [comment]
Try [`mul_to`](https://docs.rs/nalgebra/latest/nalgebra/base/struct.Matrix.html#method.mul_to)?

**Comment by sebcrozet** [comment]
@IvaYan Doing:
```rust
result_row = m1.row_mut(i) / m2.row(0);
```
cannot work because you are trying to assign different types (Rust doesn’t have overloading of the `=` operator like in C++).
Instead, you can do:
```rust
result_row.copy_from(&m1.row(i).component_div(&m2))
```

To avoid any kind of intermediate allocation, you could do this instead:
```rust
let mut result = m1.clone_owned();
for result_row in result.rows_mut() {
    result_row.component_div_assign(&m2);
}
