### ISSUE TITLE
What are the plans for the next release?

### ISSUE THREAD

**Issue by patowen** [dimforge/nalgebra#1157]
Since the last release, almost two months have passed, and 7 PRs have been merged. There is a PR I have in another project that is waiting on this next release, which is why I'm interested, but it's not time sensitive.

Are there any existing plans for a 0.31.2 or 0.32.0 release? If not, what tasks remain until the code base is ready for a new release? Since I would benefit from this new release, in the spirit of open source, is there anything I would be able to do to help?

**Comment by patowen** [comment]
@sebcrozet Sorry for bumping this, but I believe that only maintainers, rather than contributors, will be able to answer this question, and I'm not sure whether you saw it.

**Comment by sebcrozet** [comment]
Thank you for the reminder, this issue slipped my mind.
A release 0.31.2 will be done once the CI of https://github.com/dimforge/nalgebra/pull/1161 suceeds.

**Comment by patowen** [comment]
Ah, perfect! Thanks for the followup!

**Comment by sebcrozet** [comment]
Release done.
