### ISSUE TITLE
How to replace values greater than ~

### ISSUE THREAD

**Issue by kazuki-komori** [dimforge/nalgebra#1159]
I want to replace all values greater than 0 in the matrix with 0.
Any ideas?

Specifically, this kind of processing in python's numpy.
```py
x = [0, 1, 2, -1, -2]
x[x > 0] = 0

>> x = [0, 0, 0, -1, -2]
```

**Comment by sebcrozet** [comment]
Hi! You can do `x.apply(|x| if *x > 0.0 { *x = 0.0 })` to perform the operation in-place, or `let modified_x = x.map(|x| x.min(0.0))` if you don’t need the operation to be performed in-place.

**Comment by kazuki-komori** [comment]
@sebcrozet 
Thank you very much!!
