### ISSUE TITLE
Typo in documentation for quaternion axis_angle

### ISSUE THREAD

**Issue by temportalflux** [dimforge/nalgebra#1164]
"The rotation axis and angle in ]0, pi] of this unit quaternion."
Was reading over the documentation, and it seems like "]0, pi]" should be "[0, pi]"
https://github.com/dimforge/nalgebra/blob/2f1f4414e23f64edab4a51961898986df18bec8f/src/geometry/quaternion.rs#L1326

**Comment by sebcrozet** [comment]
The `]0, pi]` bound is correct because the method returns `None` if the angle is 0.
