### ISSUE TITLE
Broadcasting of +, -, x and division operations between matrices, vectors, and scales

### ISSUE THREAD

**Issue by hunter1992** [dimforge/nalgebra#1168]
I am new to learning Rust and nalgebra.

The difficulty I'm having is: how do I add, subtract, multiply and divide a number for each element of the matrix?

For example, I have a static matrix M, and a scale n:
```let M = SMatrix::<f64, 3, 2>::from([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]).transpose();```
```let n: f64 = 10.0;```

I wanna every element in M add or subtract or times or divide n, how to do it？

**Comment by sebcrozet** [comment]
- To multiply and divide you can do: `matrix / number` or `matrix * number`.
- To add and subtract, you can do: `matrix.add_scalar(number)` or `matrix.add_scalar(-number)`.
