### ISSUE TITLE
Support half-precision fp16 behind a feature flag

### ISSUE THREAD

**Issue by farnoy** [dimforge/nalgebra#1189]
Would it make sense for the `nalgebra` ecosystem of crates to support fp16 using the [half](https://docs.rs/half/latest/half/) crate?

**Comment by Ralith** [comment]
What would the use case be? Conventional CPUs don't tend to support efficient operations on f16.

**Comment by farnoy** [comment]
To be honest, I'm only using fp16 for storage & conversions.

**Comment by sebcrozet** [comment]
Thank you for the suggestion @farnoy!
I’m closing this since nothing has to change in `nalgebra` itself to support `fp16`.
All that’s needed is for `fp16` to implement the `RealField` trait from the `simba` crate (and the traits it inherit from).
