### ISSUE TITLE
Function that converts `Matrix1` into just item?

### ISSUE THREAD

**Issue by JulianKnodt** [dimforge/nalgebra#1209]
I was looking through the docs for a function which converts `Matrix1` into a scalar, but didn't see any.
This is akin to Pytorch's `.item()`, and was wondering if it would make sense to add this (or make it more discoverable if it already exists)?

I can do `mat[(0,0)]`, but seems a bit circuitous when I know it will only have 1 element.

**Comment by sebcrozet** [comment]
Doing `mat[(0, 0)]` or `mat.m11` is the way to go. I don’t think there is any benefit to make a specific method for this.

**Comment by JulianKnodt** [comment]
Sorry to push this a bit more, but the reason that this would be added is because it provides type-safety, ensuring that the user correctly identifies that it's a `Matrix1`. For example, if I do `(v * v.transpose())[(0,0)]` instead of `(v.transpose() * v)[(0,0)]`, that will compile. If instead there was only a function on `Matrix1` that allowed access to the single element, it would ensure that a user would be guaranteed at compile time that it was a scalar.

I am willing to make a PR for this if willing.
