### ISSUE TITLE
Equivalent to cgmath::look_to_rh

### ISSUE THREAD

**Issue by KekOnTheWorld** [dimforge/nalgebra#1245]
Hello, I just stumbled over this crate searching for a math library for my project using WGPU. I thought this would be a better fit for this project since it looks more modern and maintained.

I wanted to create a 3D camera but didn't know how to achieve a first person experience since I didn't find something like cgmath's look_to_rh function.

Is there a sequence of transformations which I can apply to achieve this?

**Comment by sebcrozet** [comment]
Hi! It sounds like [`face_toward`](https://docs.rs/nalgebra/0.32.2/nalgebra/geometry/type.Isometry3.html#method.face_towards) would do the trick.

**Comment by KekOnTheWorld** [comment]
Yep that is exactly what I needed. Thank you
