### ISSUE TITLE
ExactSizeIterator for matrix types?

### ISSUE THREAD

**Issue by Makogan** [dimforge/nalgebra#1247]
I think the matrix types would benefit from implementing the core trait ExactSizeIterator, it would provide a generic way of determining the dimensions that would also be compatible with vectors from the stl and slices and other common list type containers.

**Comment by sebcrozet** [comment]
Agreed, that would be a good addition.

**Comment by spoloxs** [comment]
Can I get a little elaboration about this ? From understanding you want a function to know the dimension of a matrix that would be compatible for operations, like addition, multiplication etc., with a given matrix?
Is this correct?

**Comment by geo-ant** [comment]
I'll gladly work on this but I also don't quite understand what is missing from the codebase. The row, column, and elementwise iterators all implement the `ExactSizeIterator` trait. What am I missing?

**Comment by mnickrogers** [comment]
Is this not already done [here](https://github.com/dimforge/nalgebra/blob/c6ff3eeb7e527d81b3f5607adcbe217b96f81244/src/base/iter.rs#L164)? Happy to help as well, but could use a little more specificity on the expected implementation.

**Comment by Makogan** [comment]
Sorry for the delay. This was a while ago and I am trying to remember what the issue was. 
First @mnickrogers  that link is about the inner storage type implementing exact size, not the outer matrix type like DMatrix. 

The context for the request is, I was writing some generic code and needed to get the total number of elements as len. iirc I was trying to use one of the methods of the STL on a DMatrix.

**Comment by camdenmcgath** [comment]
@Makogan are you still looking for a solution implementing exact size for outer type DMatrix problem so you can use STL methods on DMatrix?

**Comment by Makogan** [comment]
> @Makogan are you still looking for a solution implementing exact size for outer type DMatrix problem so you can use STL methods on DMatrix?

I have found a work around for what I was doing and so I don't need it immediately atm. But I still think it would be nice to have.

**Comment by L00tkek** [comment]
I'm not sure if I'm understanding correctly, but it looks like this issue has been fixed since the last comment. The generic `Matrix` type has an `iter` method (see [here](https://docs.rs/nalgebra/latest/nalgebra/base/struct.Matrix.html#method.iter)) returning a `MatrixIter`, which implements `ExactSizeIterator`. You'd have to call `matrix.iter().len()` instead of just `matrix.len()`, but unless I'm not properly understanding the use case for implementing this trait, the current implementation does what we want it to.

**Comment by Ralith** [comment]
`ExactSizeIterator` indeed already exists for matrix iterators, and iterator traits don't make sense for types that aren't iterators. Not clear which this issue is intended to be about, but in either case I don't think this is actionable.
