### ISSUE TITLE
Allow angle and/or matrix to be cached in `Rotation2`

### ISSUE THREAD

**Issue by edgimar** [dimforge/nalgebra#1250]
Currently when using a `Rotation2` type, an atan2 call is performed every time `angle` is called.  For code that uses the angle frequently, this can be costly (or requires storing the angle off as a separate variable).  Ideally this value would be computed once for a given `Rotation2` matrix, and reused unless the cache becomes dirty due to changes in the `Rotation2` matrix.  This can (and probably should) also go in the other direction:  if a `Rotation2` is initialized with an angle, then just store the angle, and when needed, compute the matrix.

**Comment by sebcrozet** [comment]
Computing the matrix on-the-fly based on the angle would make applying the rotation quite expensive. Storing the matrix sin/cos in `Rotation2` is a deliberate choice to optimize for this particular use-case. If benchmarks show that there is a need to cache this angle value, then it makes sense to leave it up to the user.

**Comment by edgimar** [comment]
I'm not sure if I understand your point correctly.  It would seem that if you start with an angle, and want to apply the rotation to a point/vector, then you would need to pay the cost of converting to sin/cos at some point (either when you create the `Rotation2` instance, or when you apply the rotation).  It can also be the case that you want to work only with the angle, and don't ever need to compute the sin/cos values.  The point is to lazily compute (and cache) either angle or sin/cos as needed, but to avoid computing it if not needed.
