### ISSUE TITLE
Add a way to get a column slice

### ISSUE THREAD

**Issue by bushkov** [dimforge/nalgebra#1327]
For `Matrix` type there is no method in the current API that allows extracting a slice containing only certain column of a matrix.

It's possible to do it via combination of column, which returns a view containing the i-th column of a matrix, and as_slice, which extracts a slice containing the entire matrix entries ordered column-by-columns, methods:
```rust
matrix.column(i).as_slice()
```

However, there are situations where that approach doesn't work. One such situation is where a function needs to return slice of representing certain column:
```rust
trait MyTrait {
    fn some_func(&self, i: usize) -> &[f64];
}

struct MyStruct {
    matrix: DMatrix<f64>,
}

impl MyTrait for MyStruct {
    fn some_func(&self, i: usize) -> &[f64] {
        self.matrix.column(i).as_slice()
    }
}
```

The above code doesn't compile because `column` method creates a temporary matrix view to represent a column view and one gets the following error:
```shell
   |         self.matrix.column(i).as_slice()
   |         ---------------------^^^^^^^^^^^
   |         |
   |         returns a value referencing data owned by the current function
   |         temporary value created here

```
The temporary matrix view is dropped once the function returns and hence one cannot take its slice even though the underlying slice that stores the data isn't dropped.

There are several workarounds for this problem such as:
* Extracting a slice containing the entire matrix and then using index arithmetic get another slice representing the column. But this approach has a disadvantage that it's more complex than just calling a method with an index of a column and is error prone due to the need to do index arithmetic
* Making functions return `DVectorView<T>` instead of `&[T]`. But this approach has a disadvantage that if the callers of `some_func` just need a slice they will always need to do extra conversion from `DVectorView<T>` to `&[T]`, and another issue is when `MyTrait` is implemented by other structs that don't operate on `Matrix` and use e.g. plain `Vec<T>`, they will need to either switch to `Matrix` for their internal implementation or convert `Vec<T>` to either `DVector<T>` or `DMatrix<T>` in their implementation of `some_func`.

I think the best approach would be to add methods `column_as_slice` and `column_mut_as_slice` to `Matrix` API that allow extracting slice of a column.

**Comment by Andlon** [comment]
While I'm sympathetic to the problem, the logical extension of adding the proposed methods would mean that we'd have to provide similar methods for rows and other kind of views, bloating the already massive API surface with more functions.

While writing this, I realized that it might be possible to solve your issue with the current API. `ViewStorage` has a `::into_slice` method that *consumes* the view's storage and returns a slice. So I think you might be able to do:

```rust
    fn some_func(&self, i: usize) -> &[f64] {
        self.matrix.column(i).data.into_slice()
    }
```
Let me know if that works out for you!

**Comment by bushkov** [comment]
> While writing this, I realized that it might be possible to solve your issue with the current API. ViewStorage has a ::into_slice method that consumes the view's storage and returns a slice. So I think you might be able to do:

@Andlon Thank you for the suggestion, it does solve the issue for my use case. So, I'll close the issue.
