### ISSUE TITLE
unit quaternions and orthonormal matrices are only closed under successive multiplications in theory

### ISSUE THREAD

**Issue by tribbloid** [dimforge/nalgebra#1377]
here is a short example demonstrating the problem:

```rust

fn main() {
    use rand::Rng;

    let mut rng = rand::thread_rng();

    let mut qq = UnitQuaternion::from_euler_angles(0.0, 0.0, 0.0);

    loop {
        let u1 = rng.gen_range(-1.58f32..1.58);
        let u2 = rng.gen_range(-1.58f32..1.58);
        let u3 = rng.gen_range(-1.58f32..1.58);

        let random = UnitQuaternion::from_euler_angles(u1, u2, u3);

        qq = random * qq;

        let norm = qq.quaternion().norm();

        let error = { norm - 1.0 }.abs();

        println!("error={}", error);

        assert!(error < 0.0001);
    }
}

```

the error will gradually increase over time until it breaks. During execution none of the above quaternions will be normalised as the compiler believes that no normalisation is required after multiplying 2 unit quaternions, which is only true in theory. In practice, the numerical error in f32 multiplications will accumulate and causes the norm to drift away from 1. In the end you have a quaternion that is very far from being a UnitQuaternion but can be used like one. If you use it to represent 3D rotation in, e.g. AHRS estimation algorithm you are guaranteed to get the wrong heading

obviously this is going to be worse for fp16, fp8 or fp4, but I haven't try it yet.

I'm thinking of adding periodic normalisation in this case, but feel free to suggest a better solution

**Comment by Ralith** [comment]
See [`UnitQuaternion::renormalize`](https://docs.rs/nalgebra/latest/nalgebra/geometry/type.UnitQuaternion.html#method.renormalize).
