### ISSUE TITLE
How to construct a symmetric matrix in nalgebra?

### ISSUE THREAD

**Issue by hunter1992** [dimforge/nalgebra#1389]
My goal is to construct a symmetric matrix M, which is composed of some known submatrices.

For example, the M I'm gonna construct is

$$
M=\begin{bmatrix}
M_{11}&M_{12}\\
M_{21}&M_{22}\\
\end{bmatrix}
$$

And the submatrix $M_{ij}$ are some known submatrices:

$$
M_{11} = 
\begin{bmatrix}
a&b\\
b&a\\
\end{bmatrix}
$$

$$
M_{12} = 
\begin{bmatrix}
c&d\\
e&f\\
\end{bmatrix}
$$

$$
M_{21} = 
\begin{bmatrix}
c&e\\
d&f\\
\end{bmatrix}
$$

$$
M_{22} = 
\begin{bmatrix}
g&h\\
h&i\\
\end{bmatrix}
$$

That is to say, the final M matrix is:

$$
M=
\begin{bmatrix}
a&b&c&d\\
b&a&e&f\\
c&e&g&h\\
d&f&h&i\\
\end{bmatrix}
$$

I want to know if there is a method in nalgebra that can still efficiently construct M when the size of M is large.

In Python, the numpy has hstack or vstack function to implement my desire.
Is there a function with the same functionality in nalgebra？

**Comment by Andlon** [comment]
#1375 is ready to merge, and it'll probably make it to the next release. Hopefully this will be soon. In the meantime, you'll have to:

1. construct your output matrix with `Matrix::zeros`
2. use e.g. `.view_mut(...)` to construct a view for each block
3. populate each view with e.g. `view.copy_from(&M_11)`

Hopefully the new `stack!` macro will make this a breeze.

**Comment by Andlon** [comment]
To elaborate, since there's no example in the PR description, you'll be able to write:

```rust
let m = stack![ m11, m12;
                m21, m22 ];
```

**Comment by hunter1992** [comment]
@Andlon Thank you very much! :)
