### ISSUE TITLE
Matrix should have `sub_scalar` and `sub_scalar_mut` methods.

### ISSUE THREAD

**Issue by Sol-Ell** [dimforge/nalgebra#1400]
The `Matrix` struct currently includes the `add_scalar` and `add_scalar_mut` methods; however, it lacks the `sub_scalar` and `sub_scalar_mut` methods. Given that types such as `Matrix<usize, ..>` cannot have negative values, I believe it is essential to include this functionality.

**Comment by Sol-Ell** [comment]
For example, attempting to compile this code results in a compilation error.
```rust
use nalgebra::Matrix2;

fn main() {
    let mut addresses: Matrix2<usize> = Matrix2::new(1, 2, 3, 4);
    addresses.add_scalar_mut(-1);
    let expected = Matrix2::new(0, 1, 2, 3);
    assert_eq!(addresses, expected)
}
```

**Comment by Andlon** [comment]
My opinion is that I don't think we should strive to support matrix computations with unsigned integers. It's already difficult to ensure that scalar `usize` arithmetic does not underflow, but correct subtractive arithmetic with *matrices* requires so much care that it's simply hardly ever a good idea. I don't think we should encourage this by adding convenience functionality that supports this use case.

I'd recommend to use signed integers for matrix arithmetic, and convert only at the end, where you can check for negative results.

**Comment by Sol-Ell** [comment]
Thank you for the clarification.
