### ISSUE TITLE
Add `map_to` just like `add_to`, and `map_assign` just like `add_assign`

### ISSUE THREAD

**Issue by jimy-byerley** [dimforge/nalgebra#1412]
Hello there
Do you think such `map_to` and `map_assign` methods could be added ? Il would allow mapping without dynamic allocation and would have the same component-wise behavior as the existing `map` and the other component-wise methods.

In my use case I need to map floats to complex and clamp floats just as the following:
```rust
let a: Matrix<f32> = ...;
let b: Matrix<Complex<f32>> = ...;

a.map_assign(|x|  x.clamp(-1., 1.));
a.map_to(|x|  Complex::new(x, 0.), &mut b);
```

**Comment by Andlon** [comment]
`.map` is very useful for small stack-allocated matrices in particular. If you want to do in-place modification, you already have several tools at your disposal, for example by iterating:

```rust
// map_assign
for a_ij in a.iter_mut() {
    *a_ij = a_ij.clamp(-1.0, 1.0);
}

// map_to
for (a_ij, b_ij) in a.iter.zip(b.iter_mut()) {
    *b_ij = Complex::new(x, 0.0);
}
```

Given that the iterators offer much more flexibility, I don't think the proposed methods carry their weight. I hope this covers your use case. I'll close this for now, but I'd be happy to reopen in case I've missed an important point.

**Comment by jimy-byerley** [comment]
The only point was to simplify this by avoiding a loop and 3 lines of code where only a simple method could to the job. On one hand, `map_*` method allows to perform such operation in an expression, on the other hand you need to dedicate 3 lines of code just for this.

Event the matrix product can be written this way with 3 loops, but often it is more convenient to have it implemented as a method like currently in nalgebra. Since `Matrix` already got tons of convenience methods like this I though it was relevant. I can understand the will to keep the crate simple though ...

**Comment by Andlon** [comment]
The difference with matmul is that matmul is *not* just 3 loops. It's way more complex under the hood in order to better use cache and SIMD.

`nalgebra` has a lot of convenience methods - perhaps a bit too many. I think going forward we need to make sure that new methods really solve a significant problem.
