### ISSUE TITLE
Stuck compiling `nalgebra` on nightly

### ISSUE THREAD

**Issue by manglemix** [dimforge/nalgebra#1437]
# Repository
This affects our [repository](https://github.com/utahrobotics/lunadev-2025), and all crates contained within depending on `nalgebra`.

# Platform
I am using a MacBook M1 Pro, and I installed rust normally. As you can see from the `rust-toolchain.toml` in the repository, we are using `nightly`.

# Example
Clone the repo and run `cargo build -p lunabot`. There are no external dependencies.

# Attempted fixes
Removing native flag from `.cargo/config.toml`  
`cargo clean`

**Comment by nuudlman** [comment]
This is an issue with today's nightly. If you revert to `nightly-2024-09-06`, everything is fine again. Today's nightly also broke `-Zthreads` too :(

**Comment by nuudlman** [comment]
See https://github.com/rust-lang/rust/issues/130056

**Comment by manglemix** [comment]
> This is an issue with today's nightly. If you revert to `nightly-2024-09-06`, everything is fine again. Today's nightly also broke `-Zthreads` too :(

This worked.

**Comment by theemathas** [comment]
Maybe this should be reopened and pinned in the issues page, for better visibility?

**Comment by cybersoulK** [comment]
just ran into this too 😮
