### ISSUE TITLE
Please implement matrix operations between complex float and float number matrices

### ISSUE THREAD

**Issue by seanxnie** [dimforge/nalgebra#1452]
Hi, there,
Scalars, for example, `Complex<f64>` numbers can perform math operations with `f64`.  Is it possible to implement such operations in `algebra::base::Matrix`?
Thanks.

**Comment by sebcrozet** [comment]
Hi! This is currently not planned. Supporting multiplication between `Matrix<T1, ...>` and `Matrix<T2, ...>` would introduce a significant amount of complexity in the generics. I’d recommend converting your value based on `f64` to `Complex<f64>` before running the operation.
