### ISSUE TITLE
Documentation is missing for some functions

### ISSUE THREAD

**Issue by hadronized** [dimforge/nalgebra#202]
Take a look at [UnitQuaternion::from_scaled_axis](http://nalgebra.org/doc/nalgebra/type.UnitQuaternion.html#method.from_scaled_axis). It’s just not there :(

**Comment by sebcrozet** [comment]
Arf, that looks like a bug in rustdoc and I don't think there is a workaround! I guess I could add the list of methods on the type alias description, but that's far from optimal...

**Comment by phaazon** [comment]
Yeah, I read `libc` has a broken doc as well :/.

**Comment by sebcrozet** [comment]
I prefer to keep this issue open. Just as a reminder and to notify others until the bug is fixed.

**Comment by aepsil0n** [comment]
for reference: rust-lang/rust#32077
