### ISSUE TITLE
ngeom library

### ISSUE THREAD

**Issue by brendanzab** [dimforge/nalgebra#23]
I am seriously considering transitioning from my `cgmath` library to nalgebra, seeing as it is now insanely well polished, and it would allow me to use your collision and physics stuff without having to re-invent the wheel. Some of the things I love about `cgmath` though is:
- [points](https://github.com/bjz/cgmath-rs/blob/master/src/point.rs) as a separate concept to vectors with the following operators:
  - `(*) : Point a -> a -> Point a`
  - `(/) : Point a -> a -> Point a`
  - `(+) : Point a -> Vector a -> Point a`
  - `(-) : Point a -> Point a -> Vector a`
- Separate types for radian and degree units
- [Projection structures](https://github.com/bjz/cgmath-rs/blob/master/src/projection.rs) with conversions to matrices

These things don't really make sense for a linear algebra library, but is it possible that we could have a separate library for these?

**Comment by kvark** [comment]
@sebcrozet what do you think about `Transform` trait with `Decomposed` implementation in cgmath-rs? Do you consider this functionality to be in scope of nalgebra?
