### ISSUE TITLE
na::try_inverse does not compile with square matrices.

### ISSUE THREAD

**Issue by sebcrozet** [dimforge/nalgebra#233]
This is a bug, we need to implement the trait `alga::SquareMatrix` for `na::SquareMatrix`.

In the mean time, use the method `.try_inverse` instead of the free-function.

**Comment by pradkrish** [comment]
is this still an open issue?

**Comment by sebcrozet** [comment]
@pradkrish No, we can  close this. There is no `::try_inverse` free function any more.
