### ISSUE TITLE
SVD sorted

### ISSUE THREAD

**Issue by nilgoyette** [dimforge/nalgebra#349]
I'm porting an application from Python to Rust and I was surprised to see that I obtain the same results when I use `numpy.linalg.svd` and `nalgebra::DMatrix::SVD` but in a random order. Turns out that the order is not random at all, it's simply a [convention](https://math.stackexchange.com/questions/844289/why-diagonal-matrix-svd-sorted-from-largest-to-smallest-value#844297) to sort the `u` and `v` matrices by the singular values `s`.

I was about to code it myself because I only have 3 possible indices (using a serie of if, else if, etc.) but it's kind of an hassle. Is there some hidden code in nalgebra that does this sorting? I may have missed it.

**Comment by sebcrozet** [comment]
Well to be honest I don't remember sorting the eigenvalues. So if they are, that may be a side-effect of the implementation which I did not know about.

**Comment by nilgoyette** [comment]
No, sorry, I may have been unclear. They are NOT sorted in nalgebra, even if it's kind of a convention to do so. I'm asking if there's a tool in nalgebra to get `u` and `v` sorted by `s`. If not, maybe we should add it. I'm probably not the only one who want the results as NumPy gives them.

**Comment by sebcrozet** [comment]
Ah, ok, I misunderstood. Yes, we should definitely add a way to sort the singular values (and singular vectors accordingly)!

**Comment by nilgoyette** [comment]
Perfect. I'll try to add this feature. Meanwhile, do you (or anyone) have a better method to sort an array AND obtain the ordered indices? Anything better than that:

    // Add an index to all values and sort the tuples, so we know how it was sorted
    let mut s: Vec<(_, _)> = svd.singular_values.into_iter().enumerate().map(
        |(idx, &v)| (v, idx)
    ).collect();
    s.sort_unstable_by(|a, b| b.partial_cmp(a).unwrap());

    // Unzip the values and order
    let order: Vec<_> = s.iter().map(|t| t.1).collect();
    let s: wathever = s.iter().map(|t| t.0).collect();
    // Reorder u and v using order

I know it's working but I have the feeling that it's allocating too much.

**Comment by michael-p** [comment]
I can confirm that for many algorithms at least in computer vision (like homography or fundamental matrix estimation) this is absolutely critical because one is not really interested in the full SVD decomposition but just in, for instance, the column of V corresponding to the smallest singular value (minimum direction problem) and hence the singular values must be sorted.

**Comment by michael-p** [comment]
I just checked: LAPACK actually guarantees this: https://www.netlib.org/lapack/lug/node32.html Anyone needing a quick solution I recommend to use the SVD decomposition in the `nalgebra_lapack` crate.

**Comment by vadixidav** [comment]
@michael-p Literally ran into this issue with essential matrix estimation from 5 points over at <https://github.com/rust-cv/nister-stewenius>. I might look into making it possible to get the singular vectors out in sorted order in some way. I am also interested in adding the `kernel()` method from eigen which gives back the null space. We will want an alternate API that also allows a user-specified epsilon for when singular value is "zero". Right now nalgebra still leaves most of this up to the user, which is fine, but it would be great to have convenience functions to avoid hassle here. As someone that didn't know much about this stuff a few days ago, it would have helped a lot just to have some documented methods that explained these differences.

**Comment by timjb** [comment]
This issue should be closed because #1081 has been merged, right?

**Comment by nilgoyette** [comment]
Oh, cool! Thank you @Christopher22 :)
