### ISSUE TITLE
Source code in API documentation is not rendered

### ISSUE THREAD

**Issue by michael-p** [dimforge/nalgebra#489]
Clicking on one of the [src] links in the generated API documentation shows only the line numbers but not the actual source code, example: https://nalgebra.org/rustdoc/src/nalgebra/lib.rs.html#407-409

Tested in recent version of Firefox and Chrome on Mac OS.

**Comment by Ralith** [comment]
I think I've been seeing this issue in other crates too lately.

**Comment by waywardmonkeys** [comment]
@Andlon This can be closed, I think. It was a bug in something else at the time, not related to `nalgebra` and current docs have functioning source code in the docs.

**Comment by Andlon** [comment]
Looks like you're right, thanks @waywardmonkeys!
