### ISSUE TITLE
Feature Request: implement all the things from alga

### ISSUE THREAD

**Issue by derekdreery** [dimforge/nalgebra#511]
I was looking for implementors of `alga::linear::AffineTransformation`, but the request could equally apply to other traits. Is it part of the plan to implement them all?

**Comment by jswrenn** [comment]
I think this may be an unfortunate API discoverability issue. Although `AffineTransformation` is already implemented for [`Similarity`](https://www.nalgebra.org/rustdoc/nalgebra/geometry/struct.Similarity.html#impl-AffineTransformation%3CPoint%3CN%2C%20D%3E%3E), [`UnitQuaternion`](https://www.nalgebra.org/rustdoc/nalgebra/geometry/type.UnitQuaternion.html#impl-AffineTransformation%3CPoint%3CN%2C%20U3%3E%3E), [`UnitComplex`](https://www.nalgebra.org/rustdoc/nalgebra/geometry/type.UnitComplex.html#impl-AffineTransformation%3CPoint%3CN%2C%20U2%3E%3E), [`Rotation`](https://www.nalgebra.org/rustdoc/nalgebra/geometry/struct.Rotation.html#impl-AffineTransformation%3CPoint%3CN%2C%20D%3E%3E), [`Translation`](https://www.nalgebra.org/rustdoc/nalgebra/geometry/struct.Translation.html#impl-AffineTransformation%3CPoint%3CN%2C%20D%3E%3E), and [`Isometry`](https://www.nalgebra.org/rustdoc/nalgebra/geometry/struct.Isometry.html#impl-AffineTransformation%3CPoint%3CN%2C%20D%3E%3E), it's not really possible to get that list without grepping the nalgebra source.

To solve this, we can add this to `lib.rs`:
```rust
/// For documentation purposes only; do not rely on items from this module.
#[deprecated(note = "For documentation purposes only; do not rely on items from this module.")]
pub mod alga_documentation {
    pub use alga::*;
}
```

This will cause rustdoc to display all of the nalgebra types that implement each trait:
![screenshot--2018 12 27-15-18-27](https://user-images.githubusercontent.com/3820879/50493314-ae226e00-09ea-11e9-915a-f88c99e7003f.png)

Once [`doc_cfg`](https://github.com/rust-lang/rust/pull/53076) is stabilized, we can actually hide that module for everything except rustdoc-triggered compilations.

**Comment by derekdreery** [comment]
I see. That's unfortunate, but thanks for getting back to me! I saw no implementors in the alga docs and assumed they hadn't been implemented.

However it's great that they are already implemented! :)

**Comment by derekdreery** [comment]
It seems that the implementation of AffineTransformation for Transformation is commented out with a note saying that you need SVD, but I think SVD is implemented.

I tried to get it working but can't cope with the trait bound errors :'(

**Comment by Andlon** [comment]
Since the design of `nalgebra` has pivoted to `simba` instead of `alga`, I will close this issue.
