### ISSUE TITLE
Some `std` features of external crates aren't re-exported

### ISSUE THREAD

**Issue by alvinhochun** [dimforge/nalgebra#623]
Some functions, for example [`Complex::to_polar`](https://www.nalgebra.org/rustdoc/nalgebra/struct.Complex.html#method.to_polar), are listed in the docs, but since they are under the `std` feature of external crates (e.g. `num-complex`) and not re-exported by `nalgebra` these methods can't actually be used.

**Comment by sebcrozet** [comment]
Hi! I’m not sure I understand the problem. Does your create depend on `num-complex` too? In that case enabling its std feature should work.

**Comment by sebcrozet** [comment]
Ah, nevermind, you are referring to the `Complex` type reexported by `nalgebra`. Yeah, we should transitively enable `num-complex/std`.
