### ISSUE TITLE
Linear indexing of a matrix slice does not account for stride.

### ISSUE THREAD

**Issue by agausmann** [dimforge/nalgebra#750]
By "linear indexing", I mean using a `usize` index to access the elements of the matrix in column-major order, via `Matrix::index::<usize>`. The implementation of `MatrixIndex` for `usize` doesn't account for the stride of the underlying matrix storage; it [calls `Storage::get_unchecked_linear`](https://github.com/rustsim/nalgebra/blob/2ab82befe4b2fd8826d307048939902089f48cb3/src/base/indexing.rs#L577) directly, which then uses this index as an [offset into the storage buffer](https://github.com/rustsim/nalgebra/blob/2ab82befe4b2fd8826d307048939902089f48cb3/src/base/storage.rs#L75). 

This works fine for matrices whose strides are equal to 1 (their storage is contiguous), but for other (sub)matrices, this produces an incorrect result. Here's an example case demonstrating what happens ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5621ecfc2709167479978eecce70e3eb)):

```rust
use nalgebra::*;

fn main() {
    let mat = DMatrix::from_row_slice(3, 3, &[
        0.0, 3.0, 6.0,
        1.0, 4.0, 7.0,
        2.0, 5.0, 8.0,
    ]);
    
    // prints each value in row 1 - [1, 4, 7]
    for i in 0..3 {
        print!("{} ", mat.index((1, i)));
    }
    println!();
    
    // get a reference to row 1
    let submat = mat.index((1, ..));
    // should print the same as above,
    // instead prints contiguous values from underlying buffer,
    // not accounting for stride - [1, 2, 3]
    for i in 0..3 {
        print!("{} ", submat.index(i));
    }
    println!();
}
```

A workaround that produces the expected behavior is to just use `(row, col)` indexing - use `(0, i)` instead of `i` to access the elements of the submatrix in the example above.

To fix this, some modular arithmetic is needed - compute the row and column from the index `i` and pass those to `Storage::get_unchecked` instead which does properly apply the stride:

```rust
let (row, col) = (i / nrows, i % nrows)
```

Alternatively, if this is too much overhead, then stricter trait bounds can be added for using `usize` as an index, so that the matrix storage has to be contiguous - note this is a breaking change:

```rust
impl<...> MatrixIndex<...> for usize
where
    S: ContiguousStorage<...>
```

**Comment by agausmann** [comment]
If this is the expected behavior, then it is still unsound, since I can get a pair of `&mut N` to the same element at the same time using completely safe code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5e8042e640faab7798dbcf208e75e1c1)):

```rust
use nalgebra::*;

fn main() {
    let mut mat = DMatrix::from_row_slice(3, 3, &[
        0.0, 3.0, 6.0,
        1.0, 4.0, 7.0,
        2.0, 5.0, 8.0,
    ]);
    
    let (mut r0, mut r1) = mat.rows_range_pair_mut(0, 1);
    let a: &mut f32 = r0.index_mut(1);
    let b: &mut f32 = r1.index_mut(0);
    println!("{:p}", a);
    println!("{:p}", b);
}
```

**Comment by sebcrozet** [comment]
Thank you for pointing this out. No, this is not on purpose and is a bug.
