### ISSUE TITLE
Help with generic function

### ISSUE THREAD

**Issue by LurkerPhD** [dimforge/nalgebra#767]
Nalgebra Newbie here.

I've managed to do this
```rust
fn baz<R1, C1, R2, C2>(
    lhs: MatrixMN<f32, R1, C1>,
    // rhs: MatrixMN<f32, R2, C2>
) where
    R1: DimName,
    C1: DimName,
    R2: DimName,
    C2: DimName,
    DefaultAllocator: Allocator<f32, R1, C1>,
{
}
```
This works fine. But note that I've commented the second parameter "rhs" because I don't know how to deal with the second Allocator.

How can I deal with the second parameter? or is there a workaround? 
I known Dynamic Matrix is an option, but I prefer not to do that.

**Comment by sebcrozet** [comment]
I guess you found the solution since you closed the issue. Here it is if anyone else search for it:
```rust
fn baz<R1, C1, R2, C2>(
    lhs: MatrixMN<f32, R1, C1>,
    rhs: MatrixMN<f32, R2, C2>
) where
    R1: DimName,
    C1: DimName,
    R2: DimName,
    C2: DimName,
    DefaultAllocator: Allocator<f32, R1, C1> + Allocator<f32, R2, C2>,
{
}
```

The key is to add the second `Allocator<f32, R2, C2>` bound: ` DefaultAllocator: Allocator<f32, R1, C1> + Allocator<f32, R2, C2>`
