### ISSUE TITLE
convert RealField to f64

### ISSUE THREAD

**Issue by astraw** [dimforge/nalgebra#771]
Is there a way to convert a generic type of `RealField` to `f64`, for example via an implementation of `Into` for `TryInto`? (Also for `f32` but I just care about `f64` for now.)

I want to "escape" from the nalgebra type annotations and use other numerical libraries which do not support the `RealField` trait.

**Comment by sebcrozet** [comment]
Hi! You can use `nalgebra::try_convert` for the `RealField -> f64` conversion. Relying on `Into` and `TryInto` would not be versatile enough because of Rust orphan rules.

**Comment by astraw** [comment]
Thanks. I'm not sure how I missed that.
