### ISSUE TITLE
Convert static sized Point to dynamic？

### ISSUE THREAD

**Issue by chargerKong** [dimforge/nalgebra#778]
I see the way to define Point in the code is：
```
Point1
Point2
Point3
Point4
Point5
Point6
```
The reason for doing this because of acceleration?
So what if the Point size is too long? Can we create a Point of dynamically changing size?

**Comment by sebcrozet** [comment]
Hi!

Right now matrices (and vectors) are the only entities that can be dynamically-sized in nalgebra.
All the geometry-related types like `Point`, `Isometry`, `Rotation`, etc. must be statically sized, to keep them simpler to implement, optimize, and easier to use.

**Comment by sebcrozet** [comment]
Also note that if you want a point of dimension greater than 6, you can define it as `nalgebra::Point<f32, nalgebra::U32>` for example. It will still be statically-sized though.

**Comment by chargerKong** [comment]
Thanks!
