### ISSUE TITLE
Different result on Windows and Linux

### ISSUE THREAD

**Issue by oll3** [dimforge/nalgebra#801]
Hi and thanks for a great library!

I'm not sure this is an error (or if it's in nalgebra or somewhere else) but noticed that the below code snippet gives a different result depending on if it is executed on Linux or Windows. Tested on multiple Linux (x86_64) instances with same result. And compared to the result of a Windows 10 machine. Using rustc 1.48.0, with same result for both nalgebra 0.22 and 0.23.

```Rust
fn main() {
    let (axis, angle) = nalgebra::Unit::new_and_get([0.0, 0.0, 5.497787f32].into());
    dbg!(nalgebra::Rotation3::from_axis_angle(&axis, angle));
}
```

Windows output:
```
[src\main.rs:3] nalgebra::Rotation3::from_axis_angle(&axis, angle) = Rotation {
    matrix: Matrix {
        data: [
            0.7071067, <----
            -0.7071069,
            0.0,
            0.7071069,
            0.7071067,  <----
            0.0,
            0.0,
            0.0,
            1.0,
        ],
    },
}
```
Linux output:
```
[src/main.rs:3] nalgebra::Rotation3::from_axis_angle(&axis, angle) = Rotation {
    matrix: Matrix {
        data: [
            0.70710665,  <----
            -0.7071069,
            0.0,
            0.7071069,
            0.70710665,  <----
            0.0,
            0.0,
            0.0,
            1.0,
        ],
    },
}
```

Maybe this is expected behavior but thought I should report it anyways.

**Comment by sebcrozet** [comment]
Hi! Yes, this is to be expected. Different OS will come with different `libc`. Therefore you end up with different implementations of some functions like `sin` and `cos` which are used by `Rotation3::from_axis_angle`.

If you really need to obtain the exact same result on both OS, you can enable the `libm-force` feature. This will force `nalgebra` to use the same Rust implementation of special math functions on all platforms.

**Comment by oll3** [comment]
> 
> 
> Hi! Yes, this is to be expected. Different OS will come with different `libc`. Therefore you end up with different implementations of some functions like `sin` and `cos` which are used by `Rotation3::from_axis_angle`.
> 
> If you really need to obtain the exact same result on both OS, you can enable the `libm-force` feature. This will force `nalgebra` to use the same Rust implementation of special math functions on all platforms (though they may run slightly slower that what `libc` would give you).

Right, thanks for clarifying!

Can close this then.
