### ISSUE TITLE
Compile error regarding ComplexField on embedded target (no_std)

### ISSUE THREAD

**Issue by krcurtis** [dimforge/nalgebra#808]
Hi,

FYI, with version 0.23.1, compiling for an embedded target (ARM Cortex M4), no_std, I get a compiler error:
```rust
error[E0599]: no method named `qr` found for struct `na::Matrix<f32, na::U4, na::U4, na::ArrayStorage<f32, na::U4, na::U4>>` in the current scope
  --> src/main.rs:91:22
   |
91 |         let a_qr = A.qr();
   |                      ^^ method not found in `na::Matrix<f32, na::U4, na::U4, na::ArrayStorage<f32, na::U4, na::U4>>`
   |
   = note: the method `qr` exists but the following trait bounds were not satisfied:
           `f32: ComplexField`
```
With version 0.20, I don't get that error, and my program complies and runs fine.

**Comment by sebcrozet** [comment]
Hi!

When targetting a `no-std` environment, it is necessary to enable the `libm` feature of nalgebra explicitly now if you need methods that rely on `ComplexField` and `RealField` for the scalar type. It was automatically enabled on older versions.

**Comment by krcurtis** [comment]
I added features = ["libm"] and that worked, great!
