### ISSUE TITLE
Deserialization in serde panics in rustc 1.48+ with some enum inner types 

### ISSUE THREAD

**Issue by nicodemus26** [dimforge/nalgebra#812]
This error presents as: ```attempted to leave type `nalgebra::ArrayStorage<...>` uninitialized, which is invalid```

This line of code panics: https://github.com/dimforge/nalgebra/blob/c0f4ee6db96952ab42c3505d1647cfeda86616b1/src/base/array_storage.rs#L380

This panic is mentioned in the [1.48 detailed notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md#compatibility-notes) as
> [mem::uninitialized will now panic if any inner types inside a struct or enum disallow zero-initialization.](https://github.com/rust-lang/rust/pull/71274/)

The tracking issue for this is here: https://github.com/rust-lang/rust/issues/66151

The way `visit_seq` is implemented looks like it should correctly initialize the whole matrix or drop the partially initialized matrix and return an `Err`. Can this function use a compiler version switch to use `MaybeUninit::uninit().assume_init()` mentioned in the [std::mem::uninitialized deprecation notes](https://doc.rust-lang.org/std/mem/fn.uninitialized.html)?

**Comment by nicodemus26** [comment]
This minimal example triggers the failure:

`src/main.rs`
```
extern crate nalgebra; // 0.23.1
extern crate serde; // 1.0.117
extern crate serde_json; // 1.0.60

use nalgebra::Vector2;
use serde_derive::{Serialize, Deserialize};
use serde_json::from_str;

#[derive(Serialize, Deserialize, Debug, PartialEq, Copy, Clone)]
#[serde(tag = "letter", content = "value")]
enum Stuff {
    A(f64),
    B(f64),
}

fn main() {
    let json = r#"[{"letter":"A", "value":123.4}, {"letter":"B", "value":567.8}]"#;
    let parsed: Vector2<Stuff> = from_str(json).unwrap();
    println!("parsed: {:?}", parsed);
}
```

`Cargo.toml`
```
[package]
name = "nalgebra_issue_812"
version = "0.1.0"
authors = ["Nicodemus Paradiso <nicodemus26@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.118"
serde_json = "1.0.60"
serde_derive = "1.0.118"

[dependencies.nalgebra]
version = "0.23.1"
features = [
    "std", "serde-serialize"
]
```

**Comment by nicodemus26** [comment]
With 1.47: ```
$ rustup override set 1.47                                                                  
info: using existing install for '1.47-x86_64-unknown-linux-gnu'
info: override toolchain set to '1.47-x86_64-unknown-linux-gnu'

  1.47-x86_64-unknown-linux-gnu unchanged - rustc 1.47.0 (18bf6b4f0 2020-10-07)

$ cargo run
...
   Compiling nalgebra_issue_812 v0.1.0 (/home/nicodemus/nalgebra_bug)
    Finished dev [unoptimized + debuginfo] target(s) in 39.54s
     Running `target/debug/nalgebra_issue_812`
parsed: Ok(Matrix { data: [A(123.4), B(567.8)] })
```

**Comment by sebcrozet** [comment]
Thank you for noticing this. I will release the version 0.23.2 with a fix.
