### ISSUE TITLE
Releasing Dual Quaternions

### ISSUE THREAD

**Issue by chinedufn** [dimforge/nalgebra#818]
Hey!

Any chance at a patch release with the new DQ type?

Reason for asking is that I have some crates that I can't publish until the next `nalgebra` goes out.

Thanks

**Comment by sebcrozet** [comment]
Hi! Because the new version of `nalgebra` contains some breaking changes, it will be released at the end of the month (i.e. within the next three days). I hope this is OK with your publication plans.

**Comment by chinedufn** [comment]
Yup - thank you for the heads up

**Comment by sebcrozet** [comment]
This has been released today with the version 0.24.0 of `nalgebra`.
