### ISSUE TITLE
from_slice for VectorN ? 

### ISSUE THREAD

**Issue by WeiPhil** [dimforge/nalgebra#833]
Hello,
I am trying to create a wrapper around the VectorN as follow:
`pub struct Wrapper<N>(VectorN<f32, N>)
where
    N: DimName,
    DefaultAllocator: Allocator<f32, N>;`

However, how can I initialize my Wrapper with custom data without knowing the concrete size? For example repeat would work fine: 

`pub fn repeat(value: f32) -> Wrapper<N> {
        Wrapper(VectorN::repeat(value))
    }`
   
but from_slice
    
`pub fn from_slice(data: &[f32]) -> Wrapper<N> {
        Wrapper(VectorN::from_slice(data))
    }`    

doesn't seem to exist for VectorN. Is there any other way I can initialize it with different values?
Best,
Philippe

**Comment by sebcrozet** [comment]
Hi!
It looks like we have not implemented `from_slice` for owned matrices yet. One alternative would be to do: `VectorN::from_fn(|i, _|| data[i])`, or `VectorN::from_iterator(slice.iter().cloned())`.

**Comment by WeiPhil** [comment]
That will do the trick, thanks!
