### ISSUE TITLE
compiling nalgebra 0.25 on no_std: getrandom 0.2.2 compile error "target is not supported"

### ISSUE THREAD

**Issue by astraw** [dimforge/nalgebra#840]
With nalgebra 0.24 and earlier, I was building fine with `no_std`. With 0.25.0, I am getting the following compilation error ([full logs here](https://github.com/strawlab/cam-geom/pull/4/checks?check_run_id=2010265242)):

```
 error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.2/src/lib.rs:213:9
    |
213 | /         compile_error!("target is not supported, for more information see: \
214 | |                         https://docs.rs/getrandom/#unsupported-targets");
    | |_________________________________________________________________________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.2/src/lib.rs:235:5
    |
235 |     imp::getrandom_inner(dest)
    |     ^^^ use of undeclared crate or module `imp`

error: aborting due to 2 previous errors
```

The [code in question](https://github.com/strawlab/cam-geom) does not use random numbers at all. Might it be possible to move the getrandom dependency under a cargo feature flag so that `no_std` code could continue to use `nalgebra 0.25`? Or perhaps there is a better solution.

This issue came up due to a dependabot-issued pull request and our automated tests that check compilation on `no_std`. Given a previous no_std regression with simba (https://github.com/dimforge/simba/issues/14), it seems like it would be useful to add a compilation check for no_std with relevant parts of the dimforge stack.

**Comment by sebcrozet** [comment]
Thank you for reporting this issue. In its latest version, `rand` (and its `getrandom` dependency) changed the way they handle random number generation on `no_std` and WASM platforms. In particular, they recommend to enable the relevant feature by adding the `getrandom` dependency to the end-user project. See [the getrandom relevant doc section](https://docs.rs/getrandom/0.2.2/getrandom/#custom-implementations) and [that rand issue](https://github.com/rust-random/rand/issues/991#issuecomment-771386545).

Though I agree that someone who don't use random should not have to go through all this hassle. So I agree that we should make `rand` optional. I will probably publish a 0.25.1 version making `rand` optional and yank `0.25`.

> This issue came up due to a dependabot-issued pull request and our automated tests that check compilation on no_std. Given a previous no_std regression with simba (dimforge/simba#14), it seems like it would be useful to add a compilation check for no_std with relevant parts of the dimforge stack.

We [already test](https://github.com/dimforge/nalgebra/blob/dev/.github/workflows/nalgebra-ci-build.yml#L81-L96) compilation in a `no_std` environment as part of the CI, and it did succeed on the 0.25 release PR. 
Could you please detail how you build `nalgebra` when targeting `no_std`? That way I can re-use in our CI whatever you are doing that make the compilation actually fail in a case like this.

**Comment by sebcrozet** [comment]
I managed to reproduce the compiler error by targeting `thumbv7em-none-eabihf` as suggested in your project's README.

**Comment by sebcrozet** [comment]
The version 0.25.1 has been released now, making `rand` optional. The version 0.25.0 has been yanked.

**Comment by astraw** [comment]
Thank you very much. I confirm this fixes the issue.
