### ISSUE TITLE
min_const_generics sintaxe in nalgebra, removing typenum dependency

### ISSUE THREAD

**Issue by guissalustiano** [dimforge/nalgebra#852]
With new [min_const_generics stabilize](https://github.com/rust-lang/rust/pull/79135) in [rust 1.51](https://github.com/rust-lang/rust/releases/tag/1.51.0) is possible think about use `Matrix<3, 2>` sintaxe instead of current `Matrix<U3, U2>`?

**Comment by sebcrozet** [comment]
Hi! This is being worked on in #820. This will probably be complete next week. Not however that the `typenum` dependency can't be completely removed yet because of some limitations of `min_const_generics`. However the users of `nalgebra` will almost never have to use `typenum` directly any more.
