### ISSUE TITLE
Add scalar

### ISSUE THREAD

**Issue by burrbull** [dimforge/nalgebra#872]
Is there any reason why this doesn't work: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0404684238d511a8b52ad5217eefcb71

```rust
use nalgebra::SVector;

fn main() {
    let c = SVector::<_, 3>::new(1_f32, 2., 3.);
    let mut d = SVector::<_, 3>::new(4_f32, 5., 6.);
    println!("{:?}", c + d); // Works
    println!("{:?}", d + 4_f32); // Error
}
```

```
7 |     println!("{:?}", d + 4_f32); // Error
  |                        ^ no implementation for `Matrix<f32, Const<3_usize>, Const<1_usize>, ArrayStorage<f32, 3_usize, 1_usize>> + f32`
  |
  = help: the trait `Add<f32>` is not implemented for `Matrix<f32, Const<3_usize>, Const<1_usize>, ArrayStorage<f32, 3_usize, 1_usize>>`
```

**Comment by sebcrozet** [comment]
Hi! You need to use `d.add_scalar(4_f32)`, or `add_scalar_mut` for in-place addition.

**Comment by burrbull** [comment]
> Hi! You need to use `d.add_scalar(4_f32)`, or `add_scalar_mut` for in-place addition.

It is good, but it seemed to me this was working before.

**Comment by sebcrozet** [comment]
Adding a scalar has never been allowed (if it was, that was by mistake). Multiplication by scalar works though.
