### ISSUE TITLE
Approx and abs_diff_eq

### ISSUE THREAD

**Issue by WeiPhil** [dimforge/nalgebra#910]
Hi,
Before updating to 0.27.1, the approx crate and abs_diff_eq in partical was implemented for matrices but now I'm getting
```
the trait `AbsDiffEq<_>` is not implemented for `Matrix<f32, na::Const<3_usize>, na::Const<1_usize>, na::ArrayStorage<f32, 3_usize, 1_usize>>` 
```
Is this due to the const generic? Is there a simple workaround or are you planning on supporting/fixing this?
Best,
Philippe

**Comment by sebcrozet** [comment]
Hi! This should still work. Are you using the same version of `approx` than the version used by `nalgebra`?
Can you perhaps share the piece of code that generates this error?

**Comment by WeiPhil** [comment]
Hi, just revised the version and it works again. Thanks!
