### ISSUE TITLE
Scalar trait unsoundness

### ISSUE THREAD

**Issue by Andlon** [dimforge/nalgebra#957]
It struck me the other day that the `Scalar` trait in its current form is responsible for a source of unsoundness.

In particular, since `Scalar` can be safely implemented, the following compiles:

```rust
#[derive(Clone, Debug, PartialEq)]
struct S;

impl Scalar for S {
    fn is<T: Scalar>() -> bool { true }
}
```

IIRC, `nalgebra` relies on this function in several cases to specialize for e.g. `f32` or `f64`, which may lead to undefined behavior with a `Scalar` implementation like the above.

I don't think this is a big problem, because I can't imagine there's anyone out there overriding `is`, but it is nonetheless unsound. The easiest way to fix this is either to move `is` out of `Scalar` or to mark `Scalar` `unsafe`.

**Comment by sebcrozet** [comment]
That’s correct.  We should get rid of this method anyway since we can just compare `TypeId` directly instead.

**Comment by MaxVerevkin** [comment]
This is solved now, isn't it?

**Comment by sebcrozet** [comment]
That’s correct, it’s solved now. Closing.
