### ISSUE TITLE
Confusing Rotation docs due to mention of quaternions

### ISSUE THREAD

**Issue by Andlon** [dimforge/nalgebra#973]
Some of the methods in `Rotation` have docs that sound somewhat copy-pasted from similar quaternion code. For example, `from_basis_unchecked`:

> In order to get a valid unit-quaternion, the input must be an orthonormal basis, i.e., all vectors are normalized, and the are all orthogonal to each other. These invariants are not checked by this method.

Or `axis_angle`:

> The rotation axis and angle in ]0, pi] of this unit quaternion.

Or `powf`:

> Raise the quaternion to a given floating power, i.e., returns the rotation with the angle of self multiplied by n.

Similarly, `Rotation::identity` gives an example using `Quaternion::identity` instead of `Rotation::identity`! I have no idea what's going on here.

**Comment by waywardmonkeys** [comment]
This was fixed in #974 and can be closed now.

**Comment by Andlon** [comment]
Thanks @waywardmonkeys !
