### ISSUE TITLE
The Mat3x3 new function has a bug?

### ISSUE THREAD

**Issue by DarkTong** [dimforge/nalgebra#984]
https://github.com/dimforge/nalgebra/blob/1bc919e0dbf2f7e83fab8aed37c1a06fe1b4fc93/nalgebra-glm/src/constructors.rs#L106-L110

**Comment by sebcrozet** [comment]
Uh, yeah, that’s clearly wrong. Thank you for pointing this out!

**Comment by loyd** [comment]
Why tests don't catch that?
