### ISSUE TITLE
How to initialize a Matrix (no function or associated item named `new`)

### ISSUE THREAD

**Issue by giacomo-b** [dimforge/nalgebra#987]
I am trying to create a 8x8 matrix. According to the [User Guide](https://nalgebra.org/docs/user_guide/vectors_and_matrices), the first step is to declare a custom type (which works):
```rust
extern crate nalgebra as na;
use na::SMatrix;
// ...
type Matrix8x8f = SMatrix<f32, 8, 8>;
```
Now, how do I _instantiate_ a new `Matrix8x8f`?

Given the following example:
https://github.com/dimforge/nalgebra/blob/319597e137f4a9a0f82f6570ec2964aa15c5c80d/examples/matrix_construction.rs#L7
I thought something like this
```rust
let m = Matrix8x8f::new(1, 2, 3, 4, 5, 6, 7, 8,
                        1, 2, 3, 4, 5, 6, 7, 8,
                        1, 2, 3, 4, 5, 6, 7, 8,
                        1, 2, 3, 4, 5, 6, 7, 8,
                        1, 2, 3, 4, 5, 6, 7, 8,
                        1, 2, 3, 4, 5, 6, 7, 8,
                        1, 2, 3, 4, 5, 6, 7, 8,
                        1, 2, 3, 4, 5, 6, 7, 8);
```
would work, but when I try to compile the code above I get the following error:
```
error[E0599]: no function or associated item named `new` found for struct `Matrix<f32, Const<8_usize>, Const<8_usize>, ArrayStorage<f32, 8_usize, 8_usize>>` in the current scope
 --> src/main.rs:6:25
  |
6 |     let m = Matrix8x8f::new(1, 2, 3, 4, 5, 6, 7, 8,
  |                         ^^^ function or associated item not found in `Matrix<f32, Const<8_usize>, Const<8_usize>, ArrayStorage<f32, 8_usize, 8_usize>>`

error: aborting due to previous error; 1 warning emitted
```
What am I missing here? I also tried using `U8` instead of `8`, with no luck.

**Comment by Andlon** [comment]
The `MatrixMxN::new()` methods are only implemented for `M, N <= 6` if I remember correctly. If you have a larger matrix, you cannot use these. The recommended way to construct matrices based on a "literal" input is to use the new `matrix` macro, something like the following:

```rust
use nalgebra::matrix;

let m = matrix![        1, 2, 3, 4, 5, 6, 7, 8;
                        1, 2, 3, 4, 5, 6, 7, 8;
                        1, 2, 3, 4, 5, 6, 7, 8;
                        1, 2, 3, 4, 5, 6, 7, 8;
                        1, 2, 3, 4, 5, 6, 7, 8;
                        1, 2, 3, 4, 5, 6, 7, 8;
                        1, 2, 3, 4, 5, 6, 7, 8;
                        1, 2, 3, 4, 5, 6, 7, 8 ];
```

I was too lazy to re-align the entries - I just copied and modified your example.

**Comment by Andlon** [comment]
On a related note, the User guide has not been updated with the `matrix!` macro in mind. I'll make a separate issue for this.

**Comment by giacomo-b** [comment]
Thanks, you just saved my day!
