### ISSUE TITLE
decompositions consume matrix

### ISSUE THREAD

**Issue by spyqqqdia** [dimforge/nalgebra#989]
The decompositions in https://github.com/dimforge/nalgebra/blob/dev/src/linalg/decomposition.rs all consume the matrix. Is this a deliberate decision? Why would one do that?

**Comment by sebcrozet** [comment]
Yes, this is deliberate to avoid some internal allocations (often, the input matrix is modified in-place), therefore getting better performances.

If you need to keep ownership of your matrix, you can simply clone it before the decomposition, e.g., `matrix.clone().lu()`.

**Comment by spyqqqdia** [comment]
Thanks for all your work! 
Without the basic matrix algorithms we cannot do much in science and it is quite nontrivial. 

Michael Meyer 

    On Saturday, September 25, 2021, 12:15:59 PM GMT+2, Sébastien Crozet ***@***.***> wrote:  
 
 


Closed #989.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
